version: '3.2'

services:
  myproject:
    build: .
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -xe
        yarn install || yarn upgrade
        yarn run dev
    ports:
      - 3000:3000
    volumes:
      - .:/app/myproject
