version: '3.2'

services:
  dev:
    build: .
    entrypoint: 
      - /bin/sh
      - -c
      - |
        yarn
        yarn dev
    depends_on:
      - firebase-emulator
    ports:
      - 3000:3000
    volumes:
      - .:/app/bluemoon

  yarn:
    image: bluemoon_dev
    command: "yarn lint --fix"
    working_dir: /app
    volumes:
      - .:/app

  firebase-emulator:
    image: bluemoon_dev
    command:
      - /bin/sh
      - -c
      - |
        cd functions
        npm install
        npm run build
        cd ..
        firebase emulators:start --only functions,firestore
    ports:
      - 8000:8080
    volumes:
      - .:/app/bluemoon

  editor:
    image: codercom/code-server
    entrypoint:
      - /bin/sh
      - -c
      - dumb-init code-server --auth none
    ports:
      - "283:8080"
    volumes:
      - "${PWD}:/home/coder/project"
      - "${HOME}/.local/share/code-server:/home/coder/.local/share/code-server" 
