version: '3.2'

services:
  dev:
    build: .
    entrypoint: 
      - /bin/sh
      - -c
      - |
        yarn
        yarn dev
    ports:
      - 3000:3000
    volumes:
      - .:/app/bluemoon

  yarn:
    image: bluemoon_dev
    command: "yarn lint --fix"
    working_dir: /app
    volumes:
      - .:/app

  editor:
    image: codercom/code-server
    entrypoint:
      - /bin/sh
      - -c
      - dumb-init code-server --auth none --host 0.0.0.0
    ports:
      - "283:8080"
    volumes:
      - "${PWD}:/home/coder/project"
      - "${HOME}/.local/share/code-server:/home/coder/.local/share/code-server" 
