version: '3.2'

services:
  web:
    build: 'docker/web'
    entrypoint: 
      - /bin/sh
      - -c
      - |
        yarn
        yarn upgrade
        yarn dev
    depends_on:
      - firebase-emulator
    ports:
      - 3000:3000
    volumes:
      - .:/app/bluemoon

  firebase-emulator:
    build: 'docker/firebase'
    command:
      - /bin/sh
      - -c
      - |
        cd functions
        npm install
        npm run build
        cd ..
        firebase emulators:start
    ports:
      - 8000:8080
      - 5000:5000
    volumes:
      - .:/app/firebase
    
