name: Copilot PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  copilot-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Copilot PR Summary
        uses: github/copilot-pr-summary@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Request Copilot Code Review
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                team_reviewers: ['copilot']
              });
              console.log('Successfully requested Copilot code review');
            } catch (error) {
              console.log('Error requesting Copilot review:', error.message);
            }