name: Copilot PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  copilot-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - name: Request Copilot Code Review
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              // Request Copilot as a reviewer
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                reviewers: ['github-copilot[bot]']
              });
              console.log('Successfully requested Copilot code review');
            } catch (error) {
              console.log('Error requesting Copilot review:', error.message);
              // Try alternative approach
              try {
                await github.rest.issues.createComment({
                  issue_number: context.payload.pull_request.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: '@github-copilot review'
                });
                console.log('Requested Copilot review via comment');
              } catch (commentError) {
                console.log('Error creating review comment:', commentError.message);
              }
            }