name: master branch workflow
on:
  push:
    branches: 
      - master

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v4
     - name: Authenticate to GCP / Firebase
       uses: google-github-actions/setup-gcloud@v2
       with:
        service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        
     - name: Install Firebase CLI
       run: npm install -g firebase-tools

     - name: Deploy to Firebase Hosting
       run: firebase deploy --only hosting
       
