name: master branch workflow
on:
  push:
    branches: 
      - master

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v4
     - name: Decode Firebase service account key
       env:
         FIREBASE_SERVICE_ACCOUNT_KEY_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_BASE64 }}
       run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_KEY_BASE64" | base64 -d > ./firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/firebase-key.json" >> $GITHUB_ENV
     - name: Deploy to Firebase Hosting
       run: firebase deploy --only hosting
       
